Underline h2h4
front-end-by-rimantas/19-grupe-portfolio-neuron pull request #108
Opened 2020-12-14 11:55 UTC by DanielGurevich1

underline ok, bet manau kad yra univesalesnis budas. bandziau su ::after, bet nepasisieke pozicija sureguliuoti. kabejo ore :)
p sutvarkiau

liko vienas taskas, kuri kelsiu atskirai

2020-12-14 13:06 UTC, laurako14 requested changes
Footeris jau sutvarkytas atskira uzduotim, prasau daryti tik tai, kas parasyta task

2020-12-14 13:22 UTC, andrejusnec requested changes

2020-12-14 13:22 UTC, andrejusnec commented on css/components/footer.css
> +        color:grey;
Kaip paminėta, footer p tag jau sutvarkytas.

2020-12-15 10:01 UTC, laurako14 approved these changes, later dismissed

2020-12-15 11:57 UTC, andrejusnec submitted a review, later dismissed

2020-12-15 12:05 UTC, andrejusnec approved these changes
Bandom

2020-12-15 12:12 UTC, laurako14 approved these changes

2020-12-15 12:12 UTC, merged