Responsive about video
front-end-by-rimantas/19-grupe-portfolio-neuron pull request #111
Opened 2020-12-14 17:44 UTC by laurako14

About video image eina virs teksto responsive

2020-12-14 20:02 UTC, DanielGurevich1 approved these changes, later dismissed

2020-12-15 06:39 UTC, JackeviciusR requested changes, later dismissed
Apačoje rodo git konflktus

2020-12-15 12:20 UTC, laurako14 commented
> Apačoje rodo git konflktus

Isspresta

2020-12-15 12:21 UTC, andrejusnec approved these changes

2020-12-15 12:47 UTC, Zymantasdan approved these changes

2020-12-15 12:52 UTC, merged